### GET all quizzes
GET http://localhost:3100/api/quiz/get-all-quizzes

### POST a quiz /quiz/submit-quiz
POST http://localhost:3100/api/quiz/submit-quiz
Content-Type: application/json
{
     "title": "Test Quiz",
     "subject": "mesl",
     "category": "terms",
     "questions": [
       {
         "questionText": "What is 2+2?",
         "type": "multiple-choice",
         "points": 1,
         "options": [
           {
             "id": 1,
             "text": "3",
             "isCorrect": false
           },
           {
             "id": 2,
             "text": "4",
             "isCorrect": true
           }
         ]
       }
     ],
     "totalPoints": 1,
     "passingScore": 70,
     "timeLimit": 30
}

### Get a quiz with queries 
 GET http://localhost:3100/api/quiz/get-all-quizzes?subject=mesl&category=terms
 

### Get a quiz by title
 GET http://localhost:3100/api/quiz/get-all-quizzes?title=Test+Quiz


